[package]
name = "pvvortex"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
flate2 = { version = "1.0", features = ["zlib"] }
pyo3 = { version = "0.20", features = ["extension-module"] }
reqwest = { version = "0.12", features = ["blocking"] }
thiserror = "1"
url = "2"
