[package]
name = "pvvortex"
version = "0.1.0"
edition = "2024"

[dependencies]
flate2 = { version = "1.0", features = ["zlib"] }
reqwest = { version = "0.12", features = ["blocking"] }
thiserror = "1"
url = "2"
